name = "vegetables"
version = "7.4.2"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "2020 Brad Richardson"

[dependencies]
  iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", tag = "v3.0.1" }
  strff = { git = "https://gitlab.com/everythingfunctional/strff.git", tag = "v3.0.0" }
